query MyQuery {
    user(login: "fernandobelotto") {
      id
      repositories(first: 10) {
        edges {
          node {
            id
            name
            homepageUrl
            description
            url
          }
        }
      }
    }
  }